#ifndef CPPSTATUS_H
#define CPPSTATUS_H

#define CPPKONTAKTE_STUB					700

#define CPPKONTAKTE_FILE_CORRUPT			501
#define CPPKONTAKTE_FILE_IO_ERROR			500

#define CPPKONTAKTE_ILLEGAL_DATA_REQUEST	400

#define CPPKONTAKTE_MEMORY_ERROR			100
#define CPPKONTAKTE_MEMORY_ALLOC_ERROR		101

#endif
