name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: make
    - name: Run with no stdin
      run: timeout 90 ./cppKontakte.run < /dev/null